branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: 02_hello-world
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Go 1.5
  default_region: us-west-1
  profile: eb-cli
  repository: null
  sc: null
